"""Unraid API - Python client library for Unraid's official GraphQL API."""

from unraid_api.client import UnraidClient
from unraid_api.exceptions import (
    UnraidAPIError,
    UnraidAuthenticationError,
    UnraidConnectionError,
    UnraidTimeoutError,
)
from unraid_api.models import (
    ApiKeyResponse,
    ArrayCapacity,
    ArrayDisk,
    Cloud,
    CloudResponse,
    Connect,
    ContainerHostConfig,
    ContainerPort,
    DockerContainer,
    DockerNetwork,
    DynamicRemoteAccessStatus,
    Flash,
    LogFile,
    LogFileContent,
    Metrics,
    MinigraphqlResponse,
    Notification,
    NotificationOverview,
    Owner,
    ParityCheck,
    PhysicalDisk,
    Plugin,
    Registration,
    RelayResponse,
    RemoteAccess,
    ServerInfo,
    Service,
    ServiceUptime,
    Share,
    SystemInfo,
    SystemMetrics,
    UnraidArray,
    UPSDevice,
    Vars,
    VmDomain,
)

__all__ = [
    "ApiKeyResponse",
    "ArrayCapacity",
    "ArrayDisk",
    "Cloud",
    "CloudResponse",
    "Connect",
    "ContainerHostConfig",
    "ContainerPort",
    "DockerContainer",
    "DockerNetwork",
    "DynamicRemoteAccessStatus",
    "Flash",
    "LogFile",
    "LogFileContent",
    "Metrics",
    "MinigraphqlResponse",
    "Notification",
    "NotificationOverview",
    "Owner",
    "ParityCheck",
    "PhysicalDisk",
    "Plugin",
    "Registration",
    "RelayResponse",
    "RemoteAccess",
    "ServerInfo",
    "Service",
    "ServiceUptime",
    "Share",
    "SystemInfo",
    "SystemMetrics",
    "UPSDevice",
    "UnraidAPIError",
    "UnraidArray",
    "UnraidAuthenticationError",
    "UnraidClient",
    "UnraidConnectionError",
    "UnraidTimeoutError",
    "Vars",
    "VmDomain",
]

__version__ = "1.3.0"
